-- test_gen_meta.lua — tests gen_meta.lua and nothing else.

package.path = "src/sunconfig/lib/?.lua;tests/?.lua;" .. package.path
local T = require("helpers")
local schema = require("schema")
local gen_meta = require("gen_meta")

T.suite("gen_meta")

T.case("golden output for the default config", function()
    local cfg = assert(schema.validate({}))
    local want = "# Generated by sunconfig -- DO NOT EDIT.\n"
        .. "# Edit /etc/sunshine/*.lua and run `sunconfig build` instead.\n"
        .. "# security_* keys are recorded but not enforced until Stage 10.\n"
        .. "desktop_environment=xfce\n"
        .. "desktop_font=Open Sans\n"
        .. "desktop_terminal=zsh\n"
        .. "security_allow_root_override=no\n"
        .. "security_kerrnil=no\n"
    T.eq(gen_meta.generate(cfg), want)
end)

T.case("booleans render as yes/no", function()
    local cfg = assert(schema.validate({
        security = { kerrnil = true, allow_root_override = true },
    }))
    local out = gen_meta.generate(cfg)
    T.match(out, "security_kerrnil=yes\n")
    T.match(out, "security_allow_root_override=yes\n")
end)

T.case("desktop values flow through", function()
    local cfg = assert(schema.validate({
        desktop = { environment = "none", font = "Inter", terminal = "sh" },
    }))
    local out = gen_meta.generate(cfg)
    T.match(out, "desktop_environment=none\n")
    T.match(out, "desktop_font=Inter\n")
    T.match(out, "desktop_terminal=sh\n")
end)

T.case("generation is deterministic", function()
    local cfg = assert(schema.validate({}))
    T.eq(gen_meta.generate(cfg), gen_meta.generate(cfg))
end)

T.case("rejects configs missing desktop or security", function()
    T.not_ok(pcall(gen_meta.generate, {}))
    T.not_ok(pcall(gen_meta.generate, { desktop = {} }))
    T.not_ok(pcall(gen_meta.generate, nil))
end)

T.case("rejects non-boolean security values smuggled past the schema", function()
    local cfg = assert(schema.validate({}))
    cfg.security.kerrnil = "yes"
    T.not_ok(pcall(gen_meta.generate, cfg))
end)

T.case("rejects empty desktop fields smuggled past the schema", function()
    local cfg = assert(schema.validate({}))
    cfg.desktop.font = ""
    T.not_ok(pcall(gen_meta.generate, cfg))
end)

T.finish()
