-- test_gen_rcconf.lua — tests gen_rcconf.lua and nothing else.

package.path = "src/sunconfig/lib/?.lua;tests/?.lua;" .. package.path
local T = require("helpers")
local schema = require("schema")
local gen_rcconf = require("gen_rcconf")

local function cfg_with_hostname(name)
    return assert(schema.validate({ system = { hostname = name } }))
end

T.suite("gen_rcconf")

T.case("golden output for the default hostname", function()
    local want = "# Generated by sunconfig -- DO NOT EDIT.\n"
        .. "# Edit /etc/sunshine/*.lua and run `sunconfig build` instead.\n"
        .. "# Transitional file: service enablement lives in /service (runit).\n"
        .. 'hostname="sunshine"\n'
    T.eq(gen_rcconf.generate(cfg_with_hostname("sunshine")), want)
end)

T.case("hostname is taken from the config", function()
    T.match(gen_rcconf.generate(cfg_with_hostname("web-01.example.org")),
        '\nhostname="web%-01%.example%.org"\n$')
end)

T.case("output ends with exactly one newline", function()
    local out = gen_rcconf.generate(cfg_with_hostname("a"))
    T.match(out, '[^\n]\n$')
end)

T.case("generation is deterministic", function()
    local c = cfg_with_hostname("same")
    T.eq(gen_rcconf.generate(c), gen_rcconf.generate(c))
end)

T.case("rejects a config without a system table", function()
    local ok, err = pcall(gen_rcconf.generate, {})
    T.not_ok(ok)
    T.match(tostring(err), "normalized config")
end)

T.case("rejects non-table input", function()
    T.not_ok(pcall(gen_rcconf.generate, "x"))
    T.not_ok(pcall(gen_rcconf.generate, nil))
end)

T.case("rejects an invalid hostname smuggled past the schema", function()
    local c = cfg_with_hostname("ok")
    c.system.hostname = 'evil"\nrogue_enable="YES'
    local ok, err = pcall(gen_rcconf.generate, c)
    T.not_ok(ok)
    T.match(tostring(err), "hostname")
end)

T.finish()
