-- test_gen_runit.lua — tests gen_runit.lua and nothing else.

package.path = "src/sunconfig/lib/?.lua;tests/?.lua;" .. package.path
local T = require("helpers")
local schema = require("schema")
local gen_runit = require("gen_runit")

local function valid(raw)
    return assert(schema.validate(raw))
end

local function find(result, path)
    for i = 1, #result.files do
        if result.files[i].path == path then return result.files[i] end
    end
    return nil
end

T.suite("gen_runit")

T.case("golden run script for a registry service", function()
    local r = gen_runit.generate(valid({
        services = { sshd = true },
        desktop = { environment = "none" },
    }))
    local run = assert(find(r, "service/sshd/run"), "run script present")
    T.eq(run.content, "#!/bin/sh\n"
        .. "# Generated by sunconfig -- DO NOT EDIT. Edit /etc/sunshine/*.lua instead.\n"
        .. "exec 2>&1\n"
        .. "exec /usr/sbin/sshd -D -e\n")
    T.eq(run.exec, true)
end)

T.case("golden log script", function()
    local r = gen_runit.generate(valid({
        services = { sshd = true },
        desktop = { environment = "none" },
    }))
    local log = assert(find(r, "service/sshd/log/run"))
    T.eq(log.content, "#!/bin/sh\n"
        .. "# Generated by sunconfig -- DO NOT EDIT. Edit /etc/sunshine/*.lua instead.\n"
        .. "exec svlogd -tt /var/log/sunshine/sshd\n")
    T.eq(log.exec, true)
end)

T.case("disabled services get a down file", function()
    local r = gen_runit.generate(valid({
        services = { sshd = false },
        desktop = { environment = "none" },
    }))
    local down = assert(find(r, "service/sshd/down"))
    T.eq(down.content, "")
    T.eq(down.exec, false)
end)

T.case("enabled services get no down file", function()
    local r = gen_runit.generate(valid({
        services = { sshd = true },
        desktop = { environment = "none" },
    }))
    T.eq(find(r, "service/sshd/down"), nil)
end)

T.case("restart=false generates a finish script", function()
    local r = gen_runit.generate(valid({
        services = { ntpd = { restart = false } },
        desktop = { environment = "none" },
    }))
    local finish = assert(find(r, "service/ntpd/finish"))
    T.match(finish.content, "exec sv down /service/ntpd\n$")
    T.eq(finish.exec, true)
end)

T.case("custom commands are used verbatim", function()
    local r = gen_runit.generate(valid({
        services = { myapp = { command = "/opt/myapp/bin/serve --fg" } },
        desktop = { environment = "none" },
    }))
    local run = assert(find(r, "service/myapp/run"))
    T.match(run.content, "exec /opt/myapp/bin/serve %-%-fg\n$")
end)

T.case("desktop xfce produces a supervised desktop service", function()
    local r = gen_runit.generate(valid({ desktop = { environment = "xfce" } }))
    local run = assert(find(r, "service/desktop/run"))
    T.match(run.content, "exec /usr/local/sbin/lightdm\n$")
    T.ok(find(r, "service/desktop/log/run"))
end)

T.case("desktop none produces no desktop service", function()
    local r = gen_runit.generate(valid({ desktop = { environment = "none" } }))
    T.eq(find(r, "service/desktop/run"), nil)
    T.deep(r.files, {})
end)

T.case("files are sorted by path and logdirs are sorted", function()
    local r = gen_runit.generate(valid({
        services = { sshd = true, ntpd = false, dbus = true },
        desktop = { environment = "xfce" },
    }))
    for i = 2, #r.files do
        T.ok(r.files[i - 1].path < r.files[i].path,
            "files sorted at " .. r.files[i].path)
    end
    T.deep(r.logdirs, {
        "var/log/sunshine/dbus",
        "var/log/sunshine/desktop",
        "var/log/sunshine/ntpd",
        "var/log/sunshine/sshd",
    })
end)

T.case("generation is deterministic", function()
    local raw = {
        services = { sshd = true, ntpd = false },
        desktop = { environment = "xfce" },
    }
    local a = gen_runit.generate(valid(raw))
    local b = gen_runit.generate(valid(raw))
    T.eq(#a.files, #b.files)
    for i = 1, #a.files do
        T.eq(a.files[i].path, b.files[i].path)
        T.eq(a.files[i].content, b.files[i].content)
    end
end)

T.case("rejects non-normalized configs", function()
    T.not_ok(pcall(gen_runit.generate, {}))
    T.not_ok(pcall(gen_runit.generate, nil))
    T.not_ok(pcall(gen_runit.generate,
        { services = { sshd = true }, desktop = { environment = "none" } }))
end)

T.case("rejects a service with no resolvable command", function()
    local cfg = valid({ services = { sshd = true }, desktop = { environment = "none" } })
    cfg.services.ghost = { enabled = true, restart = true }
    local ok, err = pcall(gen_runit.generate, cfg)
    T.not_ok(ok)
    T.match(tostring(err), "ghost")
end)

T.finish()
