#!/bin/sh
# stage-boot-chain.sh -- stage the rc(8) boot chain that bootstraps
# SunshineBSD's runtime on stock FreeBSD init.
# One job: the rc.d scripts (sunshine_etc_overlay, sunshine_provision,
# polkit, consolekit2) and the /etc/rc.conf.d enable drop-ins, written
# into $SUNISO_STAGE. This whole chain is a deliberate Stage 0/1
# stopgap, meant to be deleted outright once Stage 4 replaces rc(8)
# with runit as init's direct child (see DOCS/RUNIT.MD).
#
# Internal build step -- run via tools/make-iso.sh, which exports every
# SUNISO_* variable below.
#
# Context: fetch-pkg.sh is a plain archive extraction, so none of the
# fetched packages' own pw(8)-based pre-install scripts ran -- the
# "messagebus" (dbus), "polkitd" (polkit), and "sddm" (sddm) system
# accounts they each expect do not exist yet, nor do the +MANIFEST file
# modes and generated caches a real pkg install produces. Those can only
# be created on the real target FreeBSD system (pw(8) does not run under
# cross-execution on this Linux/WSL build host) -- which is exactly what
# etc/rc.d/sunshine_provision below does at boot, before runit starts.

set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "$here/lib.sh"

require_env SUNISO_STAGE

log "writing the sunshine_etc_overlay + sunshine_provision + runsvdir boot chain"
mkdir -p "$SUNISO_STAGE/etc/rc.d"

# Confirmed live 2026-07-18: this ISO's own /etc/fstab reads
# "/dev/iso9660/... / cd9660 ro" -- root is mounted directly off the
# optical/CD9660 image, genuinely read-only at the media level, not a
# deliberately-imposed mount option on an otherwise-writable disk. pw(8)
# fails outright (gr_tmp(): Read-only file system) trying to write
# /etc/group, so sunshine-provision-accounts can never succeed as-is.
# Stock FreeBSD already solves exactly this for /var and /tmp -- see
# etc/rc.d/var: varmfs="AUTO" detects a read-only root (a failed
# `mkdir /var/.diskless` probe) and mdmfs's a fresh memory filesystem
# directly over /var, because /var's contents are disposable (mtree
# regenerates its skeleton). /etc can't use that same trick -- its
# content (passwd, group, rc.conf, fstab, every SunshineBSD file the
# build stages) must be preserved, not wiped -- so this uses a
# unionfs mount instead: mdmfs a fresh, empty, writable filesystem at a
# scratch mountpoint under /var (guaranteed writable by the time this
# runs, per the "var" REQUIRE below) and unionfs-mount that OVER /etc.
# Reads of anything not yet written fall through to the original
# (still read-only) /etc automatically; any write goes to the new
# upper layer instead -- no need to pre-copy /etc's existing content,
# unlike a plain replace-mount. Confirmed via FreeBSD forum references
# that mdmfs (not tmpfs) is the layer type that actually works with
# unionfs.
#
# Also covers /home the same way: confirmed live 2026-07-19 that /home
# is entirely absent from the stock tree (not even an empty directory),
# so provision-accounts' supser homedir creation failed outright
# ("install: mkdir /home: Read-only file system"). stage-tooling.sh
# bakes an empty /home mountpoint into the image at build time
# (while $SUNISO_STAGE is still writable) specifically so there is
# something for this to mount onto at boot -- /home has no pre-existing
# content to preserve, but the same sunshine-etc-overlay script (fully
# parameterized via TARGET/UPPER/MFSSIZE already) handles that case
# fine, an empty lower layer just means every read is a fresh miss.
#
# Also /root: confirmed live 2026-07-19 -- `flash start xfce` (root's
# own X session, launched via xinit) failed with "Failed to open
# authorization file /root/.serverauth.NNNN: No such file or directory"
# and "xauth: error in locking authority file /root/.Xauthority". /root
# is a real base-system directory with real content (unlike /home), so
# this uses the same union-mount treatment as /etc, not the plain-empty
# treatment /home gets.
#
# Also /service: confirmed live 2026-07-19, the same way as /root --
# `runsv <name>: fatal: unable to open supervise/lock: file does not
# exist` for every single service, in an endless respawn/zombie loop
# (runsvdir keeps retrying). runsv creates its own supervise/ directory
# (lock, the ok/control FIFOs, status) the first time it starts
# supervising a service, and cannot on a read-only /service -- the
# run/down scripts sunconfig already generated are real, pre-existing
# content (same as /etc), so this gets the union-mount treatment too,
# not /home's plain-empty one.
cat > "$SUNISO_STAGE/etc/rc.d/sunshine_etc_overlay" <<'EOF'
#!/bin/sh
#
# PROVIDE: sunshine_etc_overlay
# REQUIRE: var
# BEFORE: sunshine_provision
# KEYWORD: shutdown
#
# Generated by the SunshineBSD ISO build (tools/iso/stage-boot-chain.sh).
# Makes /etc, /home, /root, and /service writable via a unionfs overlay
# when root itself is read-only (this project's live/install ISO boots
# root straight off cd9660 -- see the comment above where this file is
# generated). A no-op on a real install, where all of them are already
# on a writable ZFS root. REQUIRE: var, BEFORE: sunshine_provision --
# must finish before runsvdir ever starts scanning /service, or every
# runsv immediately dies with "unable to open supervise/lock".

. /etc/rc.subr

name="sunshine_etc_overlay"
rcvar="sunshine_etc_overlay_enable"
start_cmd="sunshine_etc_overlay_start"
stop_cmd=":"

sunshine_etc_overlay_start()
{
	/usr/local/sbin/sunshine-etc-overlay
	TARGET=/home UPPER=/var/run/sunshine_home_upper MFSSIZE=128m \
		/usr/local/sbin/sunshine-etc-overlay
	TARGET=/root UPPER=/var/run/sunshine_root_upper MFSSIZE=128m \
		/usr/local/sbin/sunshine-etc-overlay
	TARGET=/service UPPER=/var/run/sunshine_service_upper MFSSIZE=32m \
		/usr/local/sbin/sunshine-etc-overlay
}

load_rc_config "$name"
: ${sunshine_etc_overlay_enable:=NO}
run_rc_command "$1"
EOF
chmod 0755 "$SUNISO_STAGE/etc/rc.d/sunshine_etc_overlay"

cat > "$SUNISO_STAGE/etc/rc.d/sunshine_provision" <<'EOF'
#!/bin/sh
#
# PROVIDE: sunshine_provision
# REQUIRE: FILESYSTEMS sunshine_etc_overlay
# BEFORE: dbus runsvdir
# KEYWORD: shutdown
#
# Generated by the SunshineBSD ISO build (tools/iso/stage-boot-chain.sh).
# Runs the SunshineBSD provisioning steps that reconcile what
# fetch-pkg.sh's plain archive extraction could not produce: system
# accounts (provision-accounts -- dbus setuid's to messagebus, sddm
# expects its own account) and package file state (provision-pkgfiles --
# +MANIFEST setuid modes and the GLib/GTK caches whose absence killed
# every Xfce session within seconds, confirmed live 2026-07-19; see
# PLAN-03.MD). Accounts first: pkgfiles chown's
# dbus-daemon-launch-helper to the messagebus group that
# provision-accounts creates. Must run before dbus and before runsvdir
# starts supervising sddm. Also must run after sunshine_etc_overlay:
# pw(8) needs a writable /etc, which on this project's read-only-root
# live ISO only exists once that overlay is mounted (provision-pkgfiles
# mounts its own /usr/local overlay).

. /etc/rc.subr

name="sunshine_provision"
rcvar="sunshine_provision_enable"
start_cmd="sunshine_provision_start"
stop_cmd=":"

sunshine_provision_start()
{
	/usr/local/sbin/sunshine-provision-accounts
	/usr/local/sbin/sunshine-provision-pkgfiles
}

load_rc_config "$name"
: ${sunshine_provision_enable:=NO}
run_rc_command "$1"
EOF
chmod 0755 "$SUNISO_STAGE/etc/rc.d/sunshine_provision"

# dbus/polkit/consolekit2 run directly under rc(8), not runit (2026-07-19
# -- see PLAN-03.MD's Decisions section): they're foundational,
# always-on prerequisites that don't need runit's per-session
# flexibility, and bootstrapping them through runit meant also
# bootstrapping runsvdir itself from flash whenever testing skipped
# rc(8) -- real, avoidable fragility. dbus ships its own real rc.d
# script (confirmed live 2026-07-19 by fetching sysutils/dbus and
# reading it directly: its own start_precmd does `mkdir -p
# /var/lib/dbus; dbus-uuidgen --ensure`, so provision-accounts no longer
# duplicates that). polkit and consolekit2 ship no rc.d script upstream
# at all (confirmed live the same way) -- both are foreground-only
# binaries ("--no-debug"/"--no-daemon" don't daemonize them, they just
# suppress/force specific behavior), so their rc.d scripts wrap them
# with daemon(8) exactly the way x11/sddm's own real rc.d script does --
# `daemon -p pidfile` forks the wrapped program into a tracked
# background child and returns immediately; confirmed via the daemon(8)
# manual page rather than assumed, since getting this wrong would hang
# the entire boot sequence (rc(8) runs each script sequentially,
# waiting for it to return).
#
# usr/local/etc/rc.d, NOT etc/rc.d -- and this distinction is
# load-bearing, confirmed live 2026-07-19 on a booted ISO where neither
# daemon was running: /etc/rc runs rcorder in TWO passes. Pass 1 orders
# /etc/rc.d alone (up to $early_late_divider, FILESYSTEMS); pass 2
# re-orders /etc/rc.d plus local_startup dirs together, skipping
# anything pass 1 already ran. A script placed in etc/rc.d whose
# REQUIRE names a port-installed service (dbus lives in
# /usr/local/etc/rc.d) hits "requirement `dbus' has no providers" in
# pass 1 -- rcorder drops the unresolvable constraint and sorted polkit
# to POSITION 1 of the entire boot (verified with rcorder on the live
# system), so both daemons started before dbus, before their accounts
# existed, died, and were marked done, never to be retried in pass 2.
# In usr/local/etc/rc.d they are only ever ordered in pass 2, where
# dbus and runsvdir are both visible and the declared order works.
mkdir -p "$SUNISO_STAGE/usr/local/etc/rc.d"
cat > "$SUNISO_STAGE/usr/local/etc/rc.d/polkit" <<'EOF'
#!/bin/sh
#
# PROVIDE: polkit
# REQUIRE: dbus
# BEFORE: runsvdir
# KEYWORD: shutdown
#
# Generated by the SunshineBSD ISO build (tools/iso/stage-boot-chain.sh):
# polkit ships no rc.d script upstream (it's normally D-Bus-activated;
# this project runs it persistently instead, the same choice Void/Artix
# runit make for polkitd). polkitd is foreground-only, so daemon(8)
# provides the detach + pidfile tracking a normal rc.d service needs.
#
# polkit_enable="YES"

. /etc/rc.subr

name="polkit"
rcvar="polkit_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
procname="/usr/local/lib/polkit-1/polkitd"
command_args="-c -f -p ${pidfile} ${procname} --no-debug"

load_rc_config "$name"
: ${polkit_enable:=NO}
run_rc_command "$1"
EOF
chmod 0755 "$SUNISO_STAGE/usr/local/etc/rc.d/polkit"

cat > "$SUNISO_STAGE/usr/local/etc/rc.d/consolekit2" <<'EOF'
#!/bin/sh
#
# PROVIDE: consolekit2
# REQUIRE: dbus
# BEFORE: runsvdir
# KEYWORD: shutdown
#
# Generated by the SunshineBSD ISO build (tools/iso/stage-boot-chain.sh):
# consolekit2 ships no rc.d script upstream either (only an Xsession.d
# snippet for ck-launch-session, unrelated to running the system daemon
# itself). console-kit-daemon is foreground-only ("Could not daemonize:
# %s" without --no-daemon), so daemon(8) provides the detach + pidfile
# tracking here too, same as polkit above.
#
# consolekit2_enable="YES"

. /etc/rc.subr

name="consolekit2"
rcvar="consolekit2_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
procname="/usr/local/sbin/console-kit-daemon"
command_args="-c -f -p ${pidfile} ${procname} --no-daemon"

load_rc_config "$name"
: ${consolekit2_enable:=NO}
run_rc_command "$1"
EOF
chmod 0755 "$SUNISO_STAGE/usr/local/etc/rc.d/consolekit2"

# runit's own package already ships usr/local/etc/rc.d/runsvdir (confirmed
# 2026-07-18 against the live sysutils/runit package) -- no need to
# hand-write a second one. It just needs enabling, and its own default
# runsvdir_path=/var/service repointed at the /service tree sunconfig
# generates (DOCS/RUNIT.MD's documented path).
#
# Per-service /etc/rc.conf.d/<name> drop-ins (confirmed real, 2026-07-18,
# against the live ISO's own etc/rc.subr: load_rc_config sources
# ${_d}/rc.conf.d/"$_name" when present) rather than appending to a shared
# etc/rc.conf: the live ISO's etc/rc.conf already has real content
# (sendmail_enable, hostid_enable) that $SUNISO_STAGE does not know about,
# and the staged copy gets fanned onto both the live tree (pack-dist.sh,
# via `cp -Rp`, which would silently clobber the file it lands on) and
# sunshine.txz (whose base.txz sibling has its own etc/rc.conf on a real
# install). A drop-in file never collides with either.
mkdir -p "$SUNISO_STAGE/etc/rc.conf.d"
echo 'sunshine_etc_overlay_enable="YES"' > "$SUNISO_STAGE/etc/rc.conf.d/sunshine_etc_overlay"
echo 'sunshine_provision_enable="YES"' > "$SUNISO_STAGE/etc/rc.conf.d/sunshine_provision"
echo 'dbus_enable="YES"' > "$SUNISO_STAGE/etc/rc.conf.d/dbus"
echo 'polkit_enable="YES"' > "$SUNISO_STAGE/etc/rc.conf.d/polkit"
echo 'consolekit2_enable="YES"' > "$SUNISO_STAGE/etc/rc.conf.d/consolekit2"
{
    echo 'runsvdir_enable="YES"'
    echo 'runsvdir_path="/service"'
} > "$SUNISO_STAGE/etc/rc.conf.d/runsvdir"
