-- gen_meta.lua — generator for etc/sunshine.conf.
-- One job: compute the SunshineBSD meta configuration record consumed by
-- later stages (desktop session tooling, KerrNil setup). Pure function.

local util = require("util")

local M = {}

M.HEADER = "# Generated by sunconfig -- DO NOT EDIT.\n"
    .. "# Edit /etc/sunshine/*.lua and run `sunconfig build` instead.\n"
    .. "# security_* keys are recorded but not enforced until Stage 10.\n"

local function bool_word(v)
    if type(v) ~= "boolean" then
        error("gen_meta: expected boolean, got " .. type(v), 3)
    end
    if v then return "yes" end
    return "no"
end

function M.generate(cfg)
    if type(cfg) ~= "table" or type(cfg.desktop) ~= "table" or type(cfg.security) ~= "table" then
        error("gen_meta.generate: expected a normalized config table", 2)
    end
    local d, s = cfg.desktop, cfg.security
    for _, field in ipairs({ "environment", "font", "terminal" }) do
        if not util.is_nonempty_string(d[field]) then
            error("gen_meta.generate: desktop." .. field .. " must be a non-empty string", 2)
        end
    end
    local lines = {
        "desktop_environment=" .. d.environment,
        "desktop_font=" .. d.font,
        "desktop_terminal=" .. d.terminal,
        "security_allow_root_override=" .. bool_word(s.allow_root_override),
        "security_kerrnil=" .. bool_word(s.kerrnil),
    }
    return M.HEADER .. table.concat(lines, "\n") .. "\n"
end

return M
