-- gen_runit.lua — generator for the runit /service tree.
-- One job: compute every service file (run, log/run, down, finish) as
-- in-memory content, per DOCS/RUNIT.MD. Pure function, no I/O; build.lua
-- decides where the bytes land.

local util = require("util")
local registry = require("registry")

local M = {}

M.LOG_BASE = "/var/log/sunshine"

-- What `desktop.environment` maps to. lightdm stays in the foreground,
-- which is what runit supervision requires.
M.DESKTOP_COMMANDS = {
    xfce = "/usr/local/sbin/lightdm",
}

local GENERATED = "# Generated by sunconfig -- DO NOT EDIT. Edit /etc/sunshine/*.lua instead.\n"

local function run_script(command)
    return "#!/bin/sh\n" .. GENERATED
        .. "exec 2>&1\n"
        .. "exec " .. command .. "\n"
end

local function log_script(name)
    return "#!/bin/sh\n" .. GENERATED
        .. "exec svlogd -tt " .. M.LOG_BASE .. "/" .. name .. "\n"
end

local function finish_script(name)
    return "#!/bin/sh\n" .. GENERATED
        .. "# One-shot service: stay down after exit instead of restarting.\n"
        .. "exec sv down /service/" .. name .. "\n"
end

local function service_files(files, name, svc)
    local ok, why = util.valid_service_name(name)
    if not ok then error("gen_runit: " .. why, 3) end
    local command = svc.command
    if command == nil then
        local entry = registry.get(name)
        if not entry then
            error(("gen_runit: service %q has no command and is not in the registry"):format(name), 3)
        end
        command = entry.command
    end
    local cok, cwhy = util.valid_command(command)
    if not cok then error("gen_runit: service " .. name .. ": " .. cwhy, 3) end

    files[#files + 1] = { path = "service/" .. name .. "/run", content = run_script(command), exec = true }
    files[#files + 1] = { path = "service/" .. name .. "/log/run", content = log_script(name), exec = true }
    if not svc.enabled then
        files[#files + 1] = { path = "service/" .. name .. "/down", content = "", exec = false }
    end
    if svc.restart == false then
        files[#files + 1] = { path = "service/" .. name .. "/finish", content = finish_script(name), exec = true }
    end
end

-- Returns { files = { {path=, content=, exec=} ... }, logdirs = { ... } },
-- files sorted by path, logdirs sorted, both relative to the staging root.
function M.generate(cfg)
    if type(cfg) ~= "table" or type(cfg.services) ~= "table" or type(cfg.desktop) ~= "table" then
        error("gen_runit.generate: expected a normalized config table", 2)
    end

    local files, logdirs = {}, {}
    local names = util.sorted_keys(cfg.services)
    for i = 1, #names do
        local name = names[i]
        local svc = cfg.services[name]
        if type(svc) ~= "table" then
            error(("gen_runit.generate: services.%s is not normalized"):format(name), 2)
        end
        service_files(files, name, svc)
        logdirs[#logdirs + 1] = "var/log/sunshine/" .. name
    end

    if cfg.desktop.environment ~= "none" then
        local command = M.DESKTOP_COMMANDS[cfg.desktop.environment]
        if not command then
            error(("gen_runit.generate: no command known for desktop environment %q")
                :format(tostring(cfg.desktop.environment)), 2)
        end
        service_files(files, "desktop", { enabled = true, restart = true, command = command })
        logdirs[#logdirs + 1] = "var/log/sunshine/desktop"
    end

    table.sort(files, function(a, b) return a.path < b.path end)
    table.sort(logdirs)
    return { files = files, logdirs = logdirs }
end

return M
