-- gen_runit.lua — generator for the runit /service tree.
-- One job: compute every service file (run, log/run, down, finish) as
-- in-memory content, per DOCS/RUNIT.MD. Pure function, no I/O; build.lua
-- decides where the bytes land.

local util = require("util")
local registry = require("registry")

local M = {}

M.LOG_BASE = "/var/log/sunshine"

local GENERATED = "# Generated by sunconfig -- DO NOT EDIT. Edit /etc/sunshine/*.lua instead.\n"

local function run_script(command)
    return "#!/bin/sh\n" .. GENERATED
        .. "exec 2>&1\n"
        .. "exec " .. command .. "\n"
end

-- The mkdir -p is load-bearing, not defensive fluff: /var is a fresh
-- memory filesystem on every live-ISO boot (stock etc/rc.d/var mdmfs's
-- over it on read-only media), so the log directories this tree was
-- generated with do not exist at runtime. svlogd exits immediately on a
-- missing directory, runsv restarts it forever, and the main service is
-- left writing into a pipe nobody reads -- which silently BLOCKS the
-- service once the pipe fills. Confirmed live 2026-07-19: every log
-- service was in a 1-second crash loop, and a service stuck writing one
-- error line sat blocked for over an hour.
local function log_script(name)
    return "#!/bin/sh\n" .. GENERATED
        .. "mkdir -p " .. M.LOG_BASE .. "/" .. name .. "\n"
        .. "exec svlogd -tt " .. M.LOG_BASE .. "/" .. name .. "\n"
end

local function finish_script(name)
    return "#!/bin/sh\n" .. GENERATED
        .. "# One-shot service: stay down after exit instead of restarting.\n"
        .. "exec sv down /service/" .. name .. "\n"
end

local function service_files(files, name, svc)
    local ok, why = util.valid_service_name(name)
    if not ok then error("gen_runit: " .. why, 3) end
    local command = svc.command
    if command == nil then
        local entry = registry.get(name)
        if not entry then
            error(("gen_runit: service %q has no command and is not in the registry"):format(name), 3)
        end
        command = entry.command
    end
    local cok, cwhy = util.valid_command(command)
    if not cok then error("gen_runit: service " .. name .. ": " .. cwhy, 3) end

    files[#files + 1] = { path = "service/" .. name .. "/run", content = run_script(command), exec = true }
    files[#files + 1] = { path = "service/" .. name .. "/log/run", content = log_script(name), exec = true }
    if not svc.enabled then
        files[#files + 1] = { path = "service/" .. name .. "/down", content = "", exec = false }
    end
    if svc.restart == false then
        files[#files + 1] = { path = "service/" .. name .. "/finish", content = finish_script(name), exec = true }
    end
end

-- Returns { files = { {path=, content=, exec=} ... }, logdirs = { ... } },
-- files sorted by path, logdirs sorted, both relative to the staging root.
function M.generate(cfg)
    if type(cfg) ~= "table" or type(cfg.services) ~= "table" or type(cfg.desktop) ~= "table" then
        error("gen_runit.generate: expected a normalized config table", 2)
    end

    local files, logdirs = {}, {}
    local names = util.sorted_keys(cfg.services)
    for i = 1, #names do
        local name = names[i]
        local svc = cfg.services[name]
        if type(svc) ~= "table" then
            error(("gen_runit.generate: services.%s is not normalized"):format(name), 2)
        end
        service_files(files, name, svc)
        logdirs[#logdirs + 1] = "var/log/sunshine/" .. name
    end

    -- desktop.environment deliberately generates NO service of its own.
    -- It used to map xfce -> a /service/desktop running lightdm -- a
    -- leftover from before SDDM was chosen. Confirmed live 2026-07-19:
    -- that service crash-looped on every boot (lightdm is not installed,
    -- and the display manager is sddm, declared like any other service
    -- in services.lua). The desktop choice still drives other
    -- generators (fonts, session defaults); the DM is just a service.

    table.sort(files, function(a, b) return a.path < b.path end)
    table.sort(logdirs)
    return { files = files, logdirs = logdirs }
end

return M
