-- gen_rcconf.lua — generator for etc/rc.conf.
-- One job: compute the transitional rc.conf content as a string. Pure
-- function, no I/O. Service enablement deliberately does NOT go here:
-- services belong to runit (/service), see DOCS/RUNIT.MD.

local util = require("util")

local M = {}

M.HEADER = "# Generated by sunconfig -- DO NOT EDIT.\n"
    .. "# Edit /etc/sunshine/*.lua and run `sunconfig build` instead.\n"
    .. "# Transitional file: service enablement lives in /service (runit).\n"

function M.generate(cfg)
    if type(cfg) ~= "table" or type(cfg.system) ~= "table" then
        error("gen_rcconf.generate: expected a normalized config table", 2)
    end
    local ok, why = util.valid_hostname(cfg.system.hostname)
    if not ok then
        error("gen_rcconf.generate: " .. why, 2)
    end
    return M.HEADER .. ('hostname="%s"\n'):format(cfg.system.hostname)
end

return M
